Avoid logging session invalidation exceptions, caused by crawler and other automated test activity, such as: (#1586)
java.lang.IllegalStateException: isNew: Session already invalidated
	at org.apache.catalina.session.StandardSession.isNew(StandardSession.java:1248) ~[catalina.jar:9.0.27]
	at org.apache.catalina.session.StandardSessionFacade.isNew(StandardSessionFacade.java:177) ~[catalina.jar:9.0.27]
	at org.labkey.api.security.AuthenticatedRequest.makeRealSession(AuthenticatedRequest.java:218) [api-20.10-SNAPSHOT.jar:20.10-SNAPSHOT]
	at org.labkey.api.security.AuthenticatedRequest.guestSession(AuthenticatedRequest.java:481) [api-20.10-SNAPSHOT.jar:20.10-SNAPSHOT]
	at org.labkey.api.security.AuthenticatedRequest.getSession(AuthenticatedRequest.java:170) [api-20.10-SNAPSHOT.jar:20.10-SNAPSHOT]

Co-authored-by: labkey-jeckels <Josh Eckels>