Remove unnecessary Tika dependency (#8153)
## Rationale
Long ago, `tika-parsers-standard-package` provided a bunch of parsers.
More recently, Tika 3.3.2, it was basically empty. As of 4.1.0, it
doesn't even supply a jar (just a POM at this package location). On my
machine, this package no longer supplying a replacement jar meant the
3.3.2 jar was left behind in my deployment folder, causing the warning
stack trace below. Not sure if others experienced that, but regardless,
let's get rid of it.
```
WARN  ServiceLoader ... failed to load service provider org.apache.tika.parser.external.CompositeExternalParser for interface org.apache.tika.parser.Parser
java.lang.ClassNotFoundException: org.apache.tika.parser.external.CompositeExternalParser
      at org.apache.tika.config.ServiceLoader.loadStaticServiceProviders(ServiceLoader.java:328)
      at org.apache.tika.parser.DefaultParser.getDefaultParsers(DefaultParser.java:115)
      at org.apache.tika.parser.DefaultParser.<init>(DefaultParser.java:66)
      at org.labkey.search.model.LuceneSearchServiceImpl.<init>(LuceneSearchServiceImpl.java:252)
      at org.labkey.search.SearchModule.init(SearchModule.java:114)
```

## Related Pull Requests
- https://github.com/LabKey/platform/pull/8141